apiVersion: apps/v1
kind: Deployment
metadata:
  name: group7-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: group7-app
  template:
    metadata:
      labels:
        app: group7-app
    spec:
      serviceAccountName: clo835
      containers:
      - name: group7-webapp
        image: 128140924817.dkr.ecr.us-east-1.amazonaws.com/project:web_app
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: GROUP_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: group_name
        - name: SLOGAN
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: slogan
        - name: BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: bucket_name
        - name: FILE_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: file_name
        - name: DBHOST
          value: "mysql-service"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: DBPWD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: DATABASE
          value: "employees"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: aws_secret_access_key
        - name: AWS_SESSION_TOKEN
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: aws_session_token
      imagePullSecrets:
      - name: ecr-secret
