apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  background_image_url: "https://github.com/111559225-myseneca/CAA900-Azure-Project/blob/main/Checkpoint2/images/parta_log_snapshot.png"
  group_name: "Group7"
  slogan: "Group7 - Empowering Excellence Together"
